### ISSUE TITLE
Family Friendly "Cheap Potato" [ENHANCEMENT REQUEST]

### ISSUE THREAD

**Issue by kiloforce** [fantasycalendar/FoundryVTT-PotatoOrNot#16]
I DnD for a family with young kids, and I have modified the "Shitty Potato" text to be just "Cheap Potato".  Others might find this change useful.  Suggest it be the default.

foundrydata/Data/modules/potato-or-not/languages/en.json
`      "PotatoOrNot.BadTitle": "Cheap Potato",`

**Comment by Haxxer** [comment]
You can always open a pull request with your changes, the module is open source

**Comment by Haxxer** [comment]
Added in 0.6.0

**Comment by oeey** [comment]
Thank you

**Comment by kiloforce** [comment]
Thank you
