### ISSUE TITLE
Change Lowest Setting to 10 FPS [ENHACEMENT REQUEST]

### ISSUE THREAD

**Issue by kiloforce** [fantasycalendar/FoundryVTT-PotatoOrNot#17]
Requesting the lowest setting ("Shitty Potato") be set to 10 FPS, instead of 20.  Seems like one would want to max out all minimal settings, right?

Or maybe there is a scientific reason for the lowest setting ("Shitty Potato") to not be at 10 FPS (instead of 20)?

**Comment by Haxxer** [comment]
Added in 0.6.0

**Comment by oeey** [comment]
Thank you

**Comment by kiloforce** [comment]
Thank you
