### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by peterpekkanen** [fantasycalendar/FoundryVTT-PotatoOrNot#22]
Hi.

When this module was applied to our foundry client it did not perform as aspected and we wish to uninstall it.
When trying to uninstall the module it does not revert all the changes since lots of other modules are still affected by the changes performed by PotatoOrNot module, leaving us stranded with a broken foundry client.

What are the specific uninstall instructions for this particular module?

**Comment by Haxxer** [comment]
Uninstalling any module that has made changes to the core settings will leave them as such.

What modules are broken? This module only changes the settings shown in the "Core" section of the game settings, so it touches **no** other modules.
