### ISSUE TITLE
Not working with foundry V11

### ISSUE THREAD

**Issue by motsog** [fantasycalendar/FoundryVTT-PotatoOrNot#23]
Stopped working with V11 on my side.

**Comment by Haxxer** [comment]
Not compatible yet:

![image](https://github.com/fantasycalendar/FoundryVTT-PotatoOrNot/assets/12858387/705b0aac-2fef-406b-886f-adfa42e59fdf)

**Comment by oeey** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-PotatoOrNot/assets/5399347/ceb8c634-f644-4c60-ae6c-68acdf2e9587)

**Comment by oeey** [comment]
Proposed pull request #24 - minimal change to support v11

**Comment by yjeroen** [comment]
I hope this officially gets pulled in :)
